-- BeyondBorders Admin Portal — Country Seed Data
-- ~40 common destination countries

insert into countries (name, iso_code, flag_emoji, region) values
  ('Canada',         'CA', '🇨🇦', 'North America'),
  ('United States',  'US', '🇺🇸', 'North America'),
  ('United Kingdom', 'GB', '🇬🇧', 'Europe'),
  ('Australia',      'AU', '🇦🇺', 'Oceania'),
  ('Germany',        'DE', '🇩🇪', 'Europe'),
  ('Netherlands',    'NL', '🇳🇱', 'Europe'),
  ('France',         'FR', '🇫🇷', 'Europe'),
  ('Ireland',        'IE', '🇮🇪', 'Europe'),
  ('Sweden',         'SE', '🇸🇪', 'Europe'),
  ('Poland',         'PL', '🇵🇱', 'Europe'),
  ('Austria',        'AT', '🇦🇹', 'Europe'),
  ('Turkey',         'TR', '🇹🇷', 'Europe'),
  ('UAE',            'AE', '🇦🇪', 'Middle East'),
  ('New Zealand',    'NZ', '🇳🇿', 'Oceania'),
  ('Japan',          'JP', '🇯🇵', 'Asia'),
  ('South Korea',    'KR', '🇰🇷', 'Asia'),
  ('Singapore',      'SG', '🇸🇬', 'Asia'),
  ('Malaysia',       'MY', '🇲🇾', 'Asia'),
  ('Italy',          'IT', '🇮🇹', 'Europe'),
  ('Spain',          'ES', '🇪🇸', 'Europe'),
  ('Portugal',       'PT', '🇵🇹', 'Europe'),
  ('Denmark',        'DK', '🇩🇰', 'Europe'),
  ('Norway',         'NO', '🇳🇴', 'Europe'),
  ('Finland',        'FI', '🇫🇮', 'Europe'),
  ('Switzerland',    'CH', '🇨🇭', 'Europe'),
  ('Belgium',        'BE', '🇧🇪', 'Europe'),
  ('Czech Republic', 'CZ', '🇨🇿', 'Europe'),
  ('Hungary',        'HU', '🇭🇺', 'Europe'),
  ('China',          'CN', '🇨🇳', 'Asia'),
  ('India',          'IN', '🇮🇳', 'Asia'),
  ('Saudi Arabia',   'SA', '🇸🇦', 'Middle East'),
  ('Qatar',          'QA', '🇶🇦', 'Middle East'),
  ('South Africa',   'ZA', '🇿🇦', 'Africa'),
  ('Brazil',         'BR', '🇧🇷', 'South America'),
  ('Mexico',         'MX', '🇲🇽', 'North America'),
  ('Argentina',      'AR', '🇦🇷', 'South America'),
  ('Chile',          'CL', '🇨🇱', 'South America'),
  ('Thailand',       'TH', '🇹🇭', 'Asia'),
  ('Vietnam',        'VN', '🇻🇳', 'Asia'),
  ('Philippines',    'PH', '🇵🇭', 'Asia');
